### ISSUE TITLE
Arm-v8 release on IzzyOnDroid

### ISSUE THREAD

**Issue by machiav3lli** [lamarios/clipious#119] opened 2023-04-14 10:41 UTC
@IzzySoft could you please add the arm-v8 apks to the app's releases. As it stands now only arm-v7 apks are collected.

If the storage may be a problem, I'd suggest to reduce the release retention for the app.

**Comment by IzzySoft** [comment] 2023-04-14 12:41
I can, but then I have to drop the armeabi one. Highlander mode here: there can only be one. My repo does not support multiple different per-ABI builds per app, sorry.

But the final word on which ABI to pick should stay with the author – so let's ask @lamarios for a decision (and while asking him: be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to [your app in my repo](https://apt.izzysoft.de/packages/com.github.lamarios.clipious/), Paul – there's ne that wuld perfectly fit next to that PlayStore one :smiley:

**Comment by lamarios** [comment] 2023-04-14 12:46
I could also build a fat apk and upload it on the release page. Would that work too ?

**Comment by lamarios** [comment] 2023-04-14 12:54
See PR: https://github.com/lamarios/clipious/pull/121/files

**Comment by lamarios** [comment] 2023-04-15 04:27
The issue is that flutter doesn't seem to support building just for arm, it's either split per abi or one fat apk.

So let's use the arm-v8 apk as the one on IzzyOnDroid

**Comment by IzzySoft** [comment] 2023-04-15 12:27
Can be done, just checked. But due to Flutter using the highest bit to indicate the ABI, there will be no way back then: armeabi has `versionCode: 1253`, arm64 has `2253` – so switching to armeabi would mean a downgrade, which Android would not permit (so it would mean uninstall/re-install). Not a big deal on an existing device (because if I'm on arm64, why should I explicitly want to switch to a 32bit build?) – but when transferring to a different device (e.g. temporary due to device repair issues).

Not saying this is a show-stopper, just mentioning the implication. Hardly affects many folks, so I'd say it's a minor thing we can accept. So shall I switch it over to arm-v8 then, @lamarios?

**Comment by lamarios** [comment] 2023-04-15 12:30
Yeah let's do it. Thanks a lot.

**Comment by IzzySoft** [comment] 2023-04-15 12:49
Done, effective with the next sync around 6 pm UTC.

**Closed** 2023-04-20 04:25 UTC
