### ISSUE TITLE
Error displaying Non-latin characters in the uploader‘s intro

### ISSUE THREAD

**Issue by Lihewin** [lamarios/clipious#408] opened 2023-12-10 15:32 UTC
**Describe the bug**
Now i only found problems in this part and i consider it being some kind of decoding problems.
![Screenshot_20231210-232736_Clipious](https://github.com/lamarios/clipious/assets/62163831/7b9f8c44-9377-4fbd-a401-2f1b1e08d7bb)

**Comment by Lihewin** [comment] 2023-12-10 15:40
![Screenshot_20231210-233809_Clipious](https://github.com/lamarios/clipious/assets/62163831/cbc3f16e-2582-458f-83e7-b80fd7b8643d)
I also found problem in Japanese characters. There might also be problems in Arabics,Thais and other none-latin characters, guessing.

**Comment by Lihewin** [comment] 2023-12-11 13:49
Errors in comments too
![Screenshot_20231211-214736_Clipious](https://github.com/lamarios/clipious/assets/62163831/f02ce39d-6259-4783-8f4a-07bfab190679)

**Comment by lamarios** [comment] 2023-12-14 09:35
hmm, this is strange. I can't reproduce this one on both phone and emulator:
![image](https://github.com/lamarios/clipious/assets/1192563/20778fe2-d64f-40bb-9630-2b19ff3a295d)

![image](https://github.com/lamarios/clipious/assets/1192563/f8636377-f1bd-4ce8-9334-d7e197631de5)


![image](https://github.com/lamarios/clipious/assets/1192563/5dd14ffe-cba1-4b4e-9dbc-055237f8c37b)


If you have the latest version, can you use the copy settings as JSON  and paste it here. 

Also is it your own private server or a public one ? So i could try there directly.

**Comment by Lihewin** [comment] 2023-12-14 10:38
Yes, you are right, problem disappeared after changing to another public server.I was using the public server https://invidious.asir.dev. However, using this server directly from the browser wont encounter the problem of bad encoding.

**Comment by lamarios** [comment] 2023-12-14 10:39
great, let me check

**Comment by lamarios** [comment] 2023-12-14 10:53
interesting. the description from api is different
from my own server:
![image](https://github.com/lamarios/clipious/assets/1192563/9bc5b33a-a6d3-42f6-98ef-005c3c4f3af2)

from that public server:
![image](https://github.com/lamarios/clipious/assets/1192563/71e317d7-480e-471e-9afb-2f6c92ed5f0a)


Interestingly enough, the html description is correct on both side.

**Comment by lamarios** [comment] 2024-01-01 00:59
I'll close this at it looks like a server issue

**Closed by lamarios** 2024-01-01 00:59 UTC
Labels: bug
