### ISSUE TITLE
Adding to playlist doesn't work

### ISSUE THREAD

**Issue by popnfresh11** [lamarios/clipious#375] opened 2023-11-14 09:59 UTC
**Describe the bug**
When you click on the playlist you want to add a video to, the playlist selection sheet closes but the video doesn't get added when you go back to check the playlist 

**To Reproduce**
1. Click on 'Add to playlist '
2. Click on '[playlist]
3. Playlist sheet closes
4. Nothing happens

**Expected behavior**
Select playlist, go to playlist video that you selected to add to the playlist should be visible 

**Smartphone (please complete the following information):**
 - Device: Pixel 8 Pro
 - OS: [e.g. Android 14]

**Comment by 2000prasanth** [comment] 2023-11-15 02:26
Please provide an option to save videos in a local playlist since forwaed sync to invidious doesn't work properly

**Comment by lamarios** [comment] 2023-11-15 09:19
Something not working well there, i'll look into fixing it.

I won't be implementing  local playlists though. My goal is to implement an invidious client and it already has playlist management so i'll use that.

**Comment by popnfresh11** [comment] 2023-11-15 09:33
Amazing thank you 🙏 love the app and if you fix this it will be perfect!  Although i think i also had an issue subscribing to channels too... But that isn't as important for me personally

**Comment by lamarios** [comment] 2023-11-15 09:44
Do you use de-arrow ?  also which version is your app at ?

**Comment by popnfresh11** [comment] 2023-11-15 09:50
Nope i don't use DeArrow 

And the version of the app I'm using is 1.17.1 build 40353

**Comment by lamarios** [comment] 2023-11-15 10:31
ok, i noticed that there were some issues when connection to server was not instant, how fast is the connection to the instance you use ?

But it looks unrelated to your issues though. I suspect it's because you probably used the token method of authentication which is bugged in some specific cases since you have issues subscribing to channels as well. Can you try to log in using the cookie method  and see if the problem is still there ?

I need to add proper error handling for this part to show a dialog if something goes wrong

Also is there any error in the logs when you try to add a playlist ? ( settings > app logs (at the bottom)).

**Comment by lamarios** [comment] 2023-11-15 10:34
possible related issue: https://github.com/lamarios/clipious/issues/347 that would also apply to playlists

**Comment by popnfresh11** [comment] 2023-11-15 10:37
Im actually using my own instance

I checked the logs and i can see these two

[SEVERE] [Service] - 2023-11-15 21:34:50.050 - Error while calling service: Invalid scope 

[INFO] [Service] - 2023-11-15 21:34:50.047 - Response from POST https://xxxxxxxxxx/api/v1/auth/playlists/IVPLycvwW8vrPpRBEVb64w8Xta3xhzGiXph/videos, status: 403 

How do i login the token method? Can you forward me a link so i can read how to do it ?

**Comment by popnfresh11** [comment] 2023-11-15 10:41
Actually don't worry i logged i worked out how to log in via cookie method and yes it fixed my problem i can add videos to playlists

**Comment by lamarios** [comment] 2023-11-15 10:51
alright, great, will close the issue. It forced my to make the playlist management for a video better, so thanks :)

**Closed by lamarios** 2023-11-15 10:51 UTC
Labels: bug
